version: '3.7'
services:
  elastic:
    image: elasticsearch:6.7.1
    hostname: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    x-setup:
      - bin/magento config:set catalog/search/engine elasticsearch6
      - bin/magento config:set catalog/search/elasticsearch6_server_hostname elastic
      - bin/magento indexer:reindex catalogsearch_fulltext