version: '2'
services:
  app:
    extends:
      file: ./php.yml
      service: app
    build:
      context: ..
      dockerfile: build/php/test
    image: duhon/php:${PHP_VERSION}-test
    volumes:
      - ../etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
