version: '2'
services:
  rabbit:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "15672:15672"
#--amqp-host=“<hostname>” --amqp-port=“5672" --amqp-user=“<user_name>” --amqp-password=“<password>” --amqp-virtualhost=“/”
