version: '2'
services:
  rabbit:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "15672:15672"
#bin/magento setup:config:set --amqp-host=rabbit --amqp-user=guest --amqp-password=guest
