version: '2'
services:
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - MAGETO_INSTALL=bin/magento setup:config:set --page-cache=redis --page-cache-redis-server=redis
#bin/magento setup:config:set --page-cache=redis --page-cache-redis-server=redis
#bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis
