version: '3.7'
services:
  varnish:
    image: million12/varnish
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ${MAGENTO_PATH}/magento-docker/etc/varnish/varnish.vcl:/etc/varnish/default.vcl:ro
    x-setup:
      - bin/magento -v config:set system/full_page_cache/varnish/backend_host web
      - bin/magento -v config:set system/full_page_cache/varnish/access_list web
      - bin/magento -v config:set system/full_page_cache/varnish/backend_port 80
      - bin/magento -v config:set system/full_page_cache/caching_application 2
      - bin/magento -v setup:config:set --http-cache-hosts=varnish:80
