version: '3.7'
services:
  web:
    image: nginx:alpine
    hostname: web
    volumes:
      - ${MAGENTO_PATH}:/var/www:${FILE_SYNC}
      - ${MAGENTO_PATH}/magento-docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${MAGENTO_PATH}/magento-docker/etc/nginx/server.crt:/etc/nginx/server.crt
      - ${MAGENTO_PATH}/magento-docker/etc/nginx/server.key:/etc/nginx/server.key
      - ${MAGENTO_PATH}/magento-docker/etc/nginx/fetch_env.js:/etc/nginx/fetch_env.js
    networks:
      default:
        aliases:
          - magento.test
    ports:
      - "${WEB_PORT}:80"
      - "${WEBS_PORT}:443"
    depends_on:
      - app
#    command: nginx-debug -g 'daemon off;'
    x-hint: uncomment the line above and change error_log in nginx.conf
    x-info: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/nginx.html
  db:
    image: mariadb
    hostname: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "magento"
    shm_size: '1gb'
    volumes:
      - ${MAGENTO_PATH}/magento-docker/etc/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "${DB_PORT}:3306"
    x-hits:
      - bin/magento dev:query-log:enable and watch var/debug/db.log
    x-info: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/mysql.html
  app:
    image: duhon/php:7.3-fpm
    hostname: app
    ports:
      - "${SSH_PORT}:22"
    stop_signal: SIGKILL
    volumes:
      - ${MAGENTO_PATH}:/var/www:${FILE_SYNC}
#      - ${MAGENTO_PATH}/magento-docker/etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ${MAGENTO_PATH}/magento-docker/etc/php/tools:/usr/local/bin/magento2:ro
      - ${MAGENTO_PATH}/magento-docker/etc/php/tideways.ini:/usr/local/etc/php/conf.d/tideways.ini
      - ${MAGENTO_PATH}/magento-docker/etc/php/profiler.php:/usr/local/lib/php/header.php
      - ${MAGENTO_PATH}/magento-docker/etc/php/append.ini:/usr/local/etc/php/conf.d/append.ini
      - ${MAGENTO_PATH}/magento-docker/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ${MAGENTO_PATH}/magento-docker/etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${MAGENTO_PATH}/magento-docker/etc/php/tests/functional/phpunit.xml:/var/www/magento2ce/dev/tests/functional/phpunit.xml:rw
      - ${MAGENTO_PATH}/magento-docker/etc/php/tests/functional/config.xml:/var/www/magento2ce/dev/tests/functional/etc/config.xml:rw
      - ${MAGENTO_PATH}/magento-docker/etc/php/tests/acceptance/.env:/var/www/magento2ce/dev/tests/acceptance/.env:rw
      - ${MAGENTO_PATH}/magento-docker/etc/php/tests/integration/install-config-mysql.php:/var/www/magento2ce/dev/tests/integration/etc/install-config-mysql.php:rw
      - ${MAGENTO_PATH}/magento-docker/etc/php/tests/api-functional/install-config-mysql.php:/var/www/magento2ce/dev/tests/api-functional/config/install-config-mysql.php:rw
      - ${MAGENTO_PATH}/magento-docker/etc/php/tests/api-functional/phpunit_rest.xml:/var/www/magento2ce/dev/tests/api-functional/phpunit_rest.xml:rw
      - ${MAGENTO_PATH}/magento-docker/etc/php/tests/api-functional/phpunit_graphql.xml:/var/www/magento2ce/dev/tests/api-functional/phpunit_graphql.xml:rw
    environment:
      COMPOSER_HOME: /var/www/.composer
      PHP_IDE_CONFIG: serverName=magento.test
    command: sh -c 'service ssh start; php-fpm -R'
    x-hints:
      - magento reinstall
      - magento sample_data
      - magento page_builder
      - docker-compose scale app=0 && docker-compose scale app=1
    x-setup:
      - bin/magento config:set web/seo/use_rewrites 1
      - bin/magento config:set dev/template/allow_symlink 1
      - bin/magento config:set admin/security/admin_account_sharing 1
      - bin/magento config:set admin/security/session_lifetime 31536000
      - bin/magento config:set system/media_storage_configuration/media_database default_setup
      - bin/magento dev:query-log:enable --query-time-threshold=1
    x-info: https://devdocs.magento.com/
  varnish:
    image: million12/varnish
    depends_on:
      - web
    ports:
      - "${VARNISH_PORT}:80"
    volumes:
      - ${MAGENTO_PATH}/magento-docker/etc/varnish/varnish.vcl:/etc/varnish/default.vcl:ro
    x-hints:
      - bin/magento cache:flush
    x-setup:
      - bin/magento -v config:set system/full_page_cache/varnish/backend_host web
      - bin/magento -v config:set system/full_page_cache/varnish/access_list web
      - bin/magento -v config:set system/full_page_cache/varnish/backend_port 80
      - bin/magento -v config:set system/full_page_cache/caching_application 2
      - bin/magento -v setup:config:set --http-cache-hosts=varnish:80
    x-info: https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish.html
  mftf:
    image: selenium/standalone-chrome-debug:3.12.0
    ports:
      - "5900:5900"
    x-hints:
      - "vnc://localhost:5900 pass:secret"
      - vendor/bin/mftf run:test
    x-info: https://devdocs.magento.com/mftf/docs/introduction.html
  elastic:
    image: elasticsearch:6.7.1
    hostname: elastic
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    x-hits:
      - curl -i http://localhost:9200/_cluster/health
    x-setup:
      - bin/magento config:set catalog/search/engine elasticsearch6
      - bin/magento config:set catalog/search/elasticsearch6_server_hostname elastic
      - bin/magento indexer:reindex catalogsearch_fulltext
    x-info: https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    x-hints:
      - redis-cli monitor
      - telnet localhost 6379
    x-setup:
      - bin/magento setup:config:set --page-cache=redis --page-cache-redis-server=redis
      - bin/magento setup:config:set --session-save=redis --session-save-redis-host=redis
      - bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis
    x-info: https://devdocs.magento.com/guides/v2.3/config-guide/redis/config-redis.html
  rabbit:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "15672:15672"
    x-hints:
      - bin/magento queue:consumers:list
      - bin/magento queue:consumers:start
      - "http://localhost:15672/ user:guest pass:guest"
    x-setup:
      - bin/magento setup:config:set --amqp-host=rabbit --amqp-user=guest --amqp-password=guest
    x-info: https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html
networks:
  default:
    driver: bridge
