name: unit
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install
        working-directory: /tmp
        run: |
          set -x
          mkdir www
          cd www
          sudo chown -R $USER:root .
          chmod g+s .
          git clone https://github.com/duhon/magento-docker.git
          git clone https://github.com/magento/magento2.git magento2ce
          cp magento-docker/bundles/typical.yml magento-docker/docker-compose.yml
          cp magento-docker/.env.dist magento-docker/.env
      - name: Test
        working-directory: /tmp/www/magento-docker
        run: |
          docker-compose up --exit-code-from app
          docker-compose exec app magento reinstall
          docker-compose exec app bin/magenento test:run unit
      
