name: unit
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Prepare
        run: |
          set -x
          mkdir -p /home/runner/work/www
          sudo chown -R $USER:root /home/runner/work/www
          chmod -R g+s /home/runner/work/www
      - name: make magento2
        working-directory: /home/runner/work
        run: |
          set -x
          git clone -b 2.3-develop --single-branch https://github.com/magento/magento2.git www/magento2ce
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: make magento-docker
        working-directory: /home/runner/work
        run: |
          set -x
          mv magento-docker/magento-docker www/magento-docker
          sudo chown -R $USER:root /home/runner/work/www
          chmod -R g+s /home/runner/work/www
          ls -la www/magento-docker
      - name: Create config
        working-directory: /home/runner/work/www/magento-docker
        run: |
          set -x
          cp bundles/minimal.yml docker-compose.yml
          cp .env.dist .env
          sed -i 's/3306/33061/' .env
      - name: Set up env
        working-directory: /home/runner/work/www/magento-docker
        run: |
          set -x
          docker-compose up -d
          docker-compose exec -T app composer install
      - name: Test
        working-directory: /home/runner/work/www/magento-docker
        run: |
          set -x
          docker-compose exec -T app magento reinstall
          docker-compose exec -T app bin/magento dev:tests:run unit
      - name: Tear down env
        working-directory: /home/runner/work/www/magento-docker
        run: |
          set -x
          docker-compose down
      
