name: unit
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Prepare
        working-directory: /home/runner
        run: |
          set -x
          mkdir www
          sudo chown -R $USER:root .
          chmod g+s .
      - uses: actions/checkout@master
        with:
          repository: magento/magento2
          path: /home/runner/www/magento2ce
      - uses: actions/checkout@master
        with:
          path: /home/runner/www/magento-docker
      - name: Create config
        working-directory: /home/runner/www/magento-docker
        run: |
          set -x
          cp bundles/typical.yml docker-compose.yml
          cp .env.dist .env
          sed -i 's/3306/33061/' .env
      - name: Set up env
        working-directory: /home/runner/www/magento-docker
        run: |
          set -x
          docker-compose up -d
          docker-compose exec -T app composer install
      - name: Test
        working-directory: /home/runner/www/magento-docker
        run: |
          set -x
          docker-compose exec -T app bin/magento dev:tests:run unit
          docker-compose down
      - name: Tear down env
        working-directory: /home/runner/www/magento-docker
        run: |
          set -x
          docker-compose down
      
